---
- hosts:
    - ovs-builder
  roles:
    - { role: ovs, action: build }

- hosts:
    - ovn-node
  roles:
    - { role: ovs, action: install }

- hosts:
    - ovn-builder
  roles:
    - { role: ovn, action: build }

- hosts:
    - ovn-node
  roles:
    - rally_user
    - { role: ovn, action: install }
