- name: Install OVN Prerequisites
  yum: name="gcc,make,python-devel,openssl,openssl-devel,graphviz,autoconf,automake,redhat-rpm-config,rpm-build,rpmdevtools,bash-completion,libtool,groff,libcap-ng-devel,selinux-policy-devel,python-six,desktop-file-utils,git,python-sphinx,firewalld-filesystem,unbound,unbound-devel" state=present

- name: Clone OVN repository
  git:
    repo: "{{ovn_repo}}"
    dest: '/git/ovn'
    version: "{{ovn_branch}}"
  register: git_repo

#- block:
#  - name: Stop if git checkout has not changed
#    debug:
#      msg: "OVN git checkout has not changed. Exiting"
#  
#  - meta: end_play
#  when: not git_repo.changed

# Nothing below will execute unless the git checkout has
# changed.

- name: Create Ansible Local Facts Directory
  file: path=/etc/ansible/facts.d state=directory

- name: Initiate Build Numbering
  copy:
    content: '{ "release":"1" }'
    dest: "/etc/ansible/facts.d/ovn_builder.fact"
    force: no
 
- name: Get commit hash of HEAD
  command: chdir=/git/ovn git rev-parse --short HEAD
  register: git_hash

- name: Bootstrap OVN build
  command: chdir=/git/ovn ./boot.sh

- name: Run OVN configure script
  command: chdir=/git/ovn ./configure "{{ovn_configure_options}}"

- name: Create spec files and source tarball
  make:
    chdir: /git/ovn
    target: dist

- name: Parse out OVN version from "configure.ac"
  command: chdir=/git/ovn autoconf -t AC_INIT:'$2'
  register: version

- name: Set source directory for building
  set_fact:
    SOURCE: "/root/rpmbuild/SOURCES"

- name: Ensure build directory is present
  file:
    name: "{{SOURCE}}"
    state: directory

- name: Copy source tarball to rpm dev tree
  command: cp /git/ovn/ovn-{{version.stdout}}.tar.gz {{SOURCE}}

- name: Unarchive ovn source tarball
  unarchive:
    src: "{{SOURCE}}/ovn-{{version.stdout}}.tar.gz"
    dest: "{{SOURCE}}"
    remote_src: yes

- name: Update release number in spec files
  lineinfile:
    path: "{{SOURCE}}/ovn-{{version.stdout}}/rhel/ovn-fedora.spec"
    regexp: '^Release:'
    line: "Release: {{ ansible_local.ovn_builder.release }}_{{ ovn_branch }}_{{ git_hash.stdout }}"

- name: Clear out old RPMs
  file:
    name: "/root/rpmbuild/RPMS/"
    state: absent

- name: Build OVN RPMs
  shell: OVN_CFLAGS="-fno-omit-frame-pointer" rpmbuild -bb --without check rhel/ovn-fedora.spec
  args:
    chdir: "{{SOURCE}}/ovn-{{version.stdout}}"

- name: Bump up Build Number
  copy:
    content: '{ "release":"{{ansible_local.ovn_builder.release|int+1}}" }'
    dest: "/etc/ansible/facts.d/ovn_builder.fact"

- name: Copy Built RPMs to local host
  synchronize:
    src: '/root/rpmbuild/RPMS'
    dest: '/tmp/'
    mode: pull

